# Generated by Django 4.0.1 on 2022-01-14 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.TextField()),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('state', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OlaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('grantName', models.TextField()),
                ('provider', models.TextField()),
                ('resource', models.TextField()),
                ('resources', models.TextField()),
                ('site', models.TextField()),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
