# Generated by Django 4.0.1 on 2022-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.TextField()),
                ('status', models.TextField()),
                ('type', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('end', models.DateTimeField()),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('state', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('teamId', models.TextField()),
                ('teamLeaders', models.TextField()),
                ('teamMembers', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OlaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('grantName', models.TextField()),
                ('provider', models.TextField()),
                ('resource', models.TextField()),
                ('resources', models.TextField()),
                ('site', models.TextField()),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('first_name', models.TextField()),
                ('i_d', models.IntegerField()),
                ('last_name', models.TextField()),
                ('login', models.TextField()),
                ('opi', models.TextField()),
                ('service_list', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
